name: DIPLOM-GURU-QA
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
#Описание джоб  
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Установить пакеты
      run: npm ci
    - name: Установить браузеры
      run: npx playwright install --with-deps
    - name: Запуск тестов
      run: npm t
    - name: Запускаем генерацию allure в одном файле
      run: npm run allureFile
      if: always()
      continue-on-error: true
      #cохраняем результаты
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      continue-on-error: true
      with:
        name: allure-report
        path: allure-report
        retention-days: 30
