name: Publish Allure Report

on:
  workflow_run:
    workflow: "DIPLOM-GURU-QA"
    types:
      - completed

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: test.yml
          name: allure-results
          path: allure-results

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@v1.6
        with:
          folder: allure-results
          github_token: ${{ secrets.TOKEN_GITHUB }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN_GITHUB }}
          publish_dir: ./allure-report
          publish_branch: gh-pages